title: Reddit’s Political Temper Check
description: A study of Sentiment, Topic Distribution, and Use of Discourse Vocabulary Across Political Communities
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-minimal
