title: Political Discourse Analysis on Reddit
description: This repository contains materials related to my study of Sentiment, Topic Distribution, and Discourse Vocabulary Across Political Communities
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-minimal
